"""fix table

Revision ID: 15d91fcf3eb9
Revises: 4ce39f688dc4
Create Date: 2025-09-09 16:42:02.238209

"""
from alembic import op
import models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15d91fcf3eb9'
down_revision: str | None = '4ce39f688dc4'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('load_balancing_model_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credential_id', models.types.StringUUID(), nullable=True))
        batch_op.add_column(sa.Column('credential_source_type', sa.String(length=40), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('load_balancing_model_configs', schema=None) as batch_op:
        batch_op.drop_column('credential_source_type')
        batch_op.drop_column('credential_id')

    # ### end Alembic commands ###
