"""1.8.0

Revision ID: 4ce39f688dc4
Revises: 7aefe33a8deb
Create Date: 2025-09-08 16:38:40.225999

"""
from alembic import op
import models
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4ce39f688dc4'
down_revision: str | None = '7aefe33a8deb'
branch_labels: str | None = None
depends_on: str | None = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('provider_credentials',
    sa.Column('id', models.types.StringUUID(), nullable=False),
    sa.Column('tenant_id', models.types.StringUUID(), nullable=False),
    sa.Column('provider_name', sa.String(length=255), nullable=False),
    sa.Column('credential_name', sa.String(length=255), nullable=False),
    sa.Column('encrypted_config', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id', name='provider_credential_pkey')
    )
    with op.batch_alter_table('provider_credentials', schema=None) as batch_op:
        batch_op.create_index('provider_credential_tenant_provider_idx', ['tenant_id', 'provider_name'], unique=False)

    op.create_table('provider_model_credentials',
    sa.Column('id', models.types.StringUUID(), nullable=False),
    sa.Column('tenant_id', models.types.StringUUID(), nullable=False),
    sa.Column('provider_name', sa.String(length=255), nullable=False),
    sa.Column('model_name', sa.String(length=255), nullable=False),
    sa.Column('model_type', sa.String(length=40), nullable=False),
    sa.Column('credential_name', sa.String(length=255), nullable=False),
    sa.Column('encrypted_config', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id', name='provider_model_credential_pkey')
    )
    with op.batch_alter_table('provider_model_credentials', schema=None) as batch_op:
        batch_op.create_index('provider_model_credential_tenant_provider_model_idx', ['tenant_id', 'provider_name', 'model_name', 'model_type'], unique=False)

    with op.batch_alter_table('provider_models', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credential_id', models.types.StringUUID(), nullable=True))
        batch_op.drop_column('encrypted_config')

    with op.batch_alter_table('providers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('credential_id', models.types.StringUUID(), nullable=True))
        batch_op.drop_column('encrypted_config')

    with op.batch_alter_table('tool_mcp_providers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timeout', sa.Float(), server_default=sa.text('30'), nullable=False))
        batch_op.add_column(sa.Column('sse_read_timeout', sa.Float(), server_default=sa.text('300'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tool_mcp_providers', schema=None) as batch_op:
        batch_op.drop_column('sse_read_timeout')
        batch_op.drop_column('timeout')

    with op.batch_alter_table('providers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encrypted_config', mysql.LONGTEXT(), nullable=True))
        batch_op.drop_column('credential_id')

    with op.batch_alter_table('provider_models', schema=None) as batch_op:
        batch_op.add_column(sa.Column('encrypted_config', mysql.LONGTEXT(), nullable=True))
        batch_op.drop_column('credential_id')

    with op.batch_alter_table('provider_model_credentials', schema=None) as batch_op:
        batch_op.drop_index('provider_model_credential_tenant_provider_model_idx')

    op.drop_table('provider_model_credentials')
    with op.batch_alter_table('provider_credentials', schema=None) as batch_op:
        batch_op.drop_index('provider_credential_tenant_provider_idx')

    op.drop_table('provider_credentials')
    # ### end Alembic commands ###
